### ISSUE TITLE
Fix `docker compose build` error on python requirements

### ISSUE THREAD

**Issue by jfwu90** [engi-network/cli#17]
Update `requirements.txt` file to fix dependency issues blocking the build. User should not be expected to install `pipenv` to build a docker container.

**Comment by garrettmaring** [comment]
@jfwu90 can you paste the error here and provide some more details on the error you encountered?

**Comment by jfwu90** [comment]
![image](https://github.com/engi-network/cli/assets/31193402/8e3d1c6d-5973-47a3-9477-b656beb02696)
