### ISSUE TITLE
Add `init` command

### ISSUE THREAD

**Issue by tjsharp1** [engi-network/cli#18]
For ease of use, create the `engi init` command, allowing a bounty creator to initialize their repository with the necessary boilerplate to work with our framework.
Need to set up docker-compose, along with `x-test-framework` attribute with correct test framework, Dockerfiles, git secret init, etc.

**Comment by garrettmaring** [comment]
Awesome. Adding/reiterating/specifying. `init` command is used by users using the CLI for the first time within a specific codebase and/or ever. It will:

1. Scaffold the appropriate docker-compose.yml and engi.Dockerfile for the detected test framework if possible.
2. Set up and prompt where necessary the environment variables, git secrets, or other local dependencies needed to run `analyze`, `draft`, `create`, and `attempt`
3. Scaffold mnemonic and chain variables using the global config (`~/.config/engi/config.yml`) if they chose so (over local MNEMONIC env)
